# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/media/images'
                permissions:
                    file:
                        public: 0644
                        private: 0644
                    dir:
                        public: 0755
                        private: 0755
            public_url_generator: App\Service\File\FlysystemPublicUrlGenerator

        video.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/storage'
                permissions:
                    file:
                        public: 0644
                        private: 0644
                    dir:
                        public: 0755
                        private: 0755