
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/var/www/html:rw
    environment:
      DATABASE_URL: "mysql://app:!ChangeMe!@database:3306/app?serverVersion=8.0.32&charset=utf8mb4"
      JELLYFIN_HOST: "http://jellyfin:8096"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8088:80"
    depends_on:
      - database
    networks:
      - default
      - momentary-network

###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - "9906:3306"
###< doctrine/doctrine-bundle ###

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # user: 1000:1000
    # network_mode: host
    ports:
      - "8096:8096"
    volumes:
      - ./docker/jellyfin/config:/config
      - ./docker/jellyfin/cache:/cache
      - ./docker/jellyfin/movies:/movies
      - ./docker/jellyfin/uploads:/uploads
    restart: unless-stopped

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

  imgproxy:
    image: darthsim/imgproxy:latest
    environment:
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /public
      IMGPROXY_ALLOW_ORIGIN: "*"
    ports:
      - "8080:8080"
    volumes:
      - ./public:/public
    networks:
      - momentary-network

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###

networks:
  momentary-network:
    external: true
