# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(PLEX_HOST): 'http://localhost:32400'
    app.frame_analysis_fps: 0.2
    app.min_scene_length_for_refinement: 2.0
    app.refined_frame_analysis_fps: 1.0
    app.aws_face_match_threshold: 80.0
    app.aws_max_faces: 15
    app.aws_quality_filter: AUTO

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\VideoAnalyzer:
        arguments:
            $filesystem: '@faces.storage'

    App\Service\PlexUploadService:
        arguments:
            $plexHost: '%env(resolve:PLEX_HOST)%'
            $plexToken: '%env(default:null:PLEX_TOKEN)%'

    App\Service\File\FileSystem:
        arguments:
            $filesystem: '@faces.storage'